Support Wildcard DNS Challenge
steinsag/hosteurope-letsencrypt pull request #29
Opened 2024-02-28 09:48 UTC by questmaster

Hi,

ich hab ein paar Ergänzungen und ein weiteres Skript eingeführt, um die Wildcard DNS Challenge zu ermöglichen. Leider funktioniert eine vollständige Automatisierung nicht, da die certbot hook scripte keine browser starten können und die Ausgaben auch nur nach Abschluss des Skripts ausgegeben werden...

IMHO solle vorher keine DNS Validation funktioniert haben, auch wenn sie konfigurierbar war. Von daher dürften die Änderungen nichts kaputt machen, sondern die DNS Challenge ermöglichen.

Ich hab es bisher nur mit Wildcard Certs getestet. Normale Zertifikate sollten aber auch möglich sein.

Bei Fragen und Problemen, lass es mich wissen...

2024-02-28 19:13 UTC, steinsag requested changes

2024-02-28 19:13 UTC, steinsag commented on neu.py
Generell würde das `neu.py` Skript inzwischen von ein paar Funktionen profitieren. Jeder baut immer noch was dazu. Vielleicht sollten wir es nochmal neu strukturieren?

2024-02-28 19:14 UTC, steinsag commented
Herzlichen Dank @questmaster für deinen Beitrag. Vielleicht kannst du meine Anregung noch aufgreifen. Ich habe inzwischen auch das Upgrade auf pypeteeeeer 2 gemergt. Vielleicht willst du nochmal mit der Version deine Lösung kurz testen?

2024-02-28 19:53 UTC, questmaster commented
Ich hatte bei mir das _set_dns_challenge_ skript schon mit pyppeteer 2.0 entwickelt, von daher sollte das zumindest passen.

2024-02-28 19:56 UTC, questmaster commented on neu.py
Joa, da könnte man einiges an Refactoring tun ;)
Ich schaue mal wie ich die Tage Zeit habe...

2024-02-28 22:52 UTC, questmaster commented on neu.py
Ich hab noch mal kurz in die Skripte reingesehen und das Refactoring war nicht riesig. Ich hab hier mal einen Vorschlag gepostet, der auf dem aktuellen PR basiert:
https://github.com/questmaster/hosteurope-letsencrypt/tree/feature/script_refactoring

Schau doch gerne mal rein, ob das so für dich passt. Wenn ja, kann ich den neuen PR stellen, wenn der aktuelle durch ist.

2024-02-29 20:34 UTC, steinsag approved these changes

2024-02-29 20:34 UTC, merged

2024-02-29 20:35 UTC, steinsag commented
@questmaster Die Änderungen in deinem Branch https://github.com/questmaster/hosteurope-letsencrypt/pull/1 sehe sehr vielversprechend aus. Ich freue mich über den PR, werde den dann aber erst Anfang nächste Woche reviewen können.